POST http://localhost:8002/wx/order/notify
Content-Type: application/json

{}

###


POST https://localhost:8002/wx/order/cancel
Content-Type: application/json
Accept: application/json

{
"orderNo":"1303949976644227072"
}