POST http://localhost:8002/wx/customer/login
Content-Type: application/json

{
"code": "oioiokbhfj"
}

###
POST http://localhost:8002/wx/order/pay
Content-Type: application/json

{
  "orderNo": "1245533809588441088",
  "totalPrice": 0.01
}

###

