spring:
  profiles:
#    active: coreprod, corecommon, dbprod
      active: coredev, corecommon, dbdev
  messages:
    encoding: UTF-8
  jackson:
    time-zone: Asia/Shanghai

server:
  port: 8083

logging:
  level:
    root:  info
    web: debug
#    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    org.idea.shower.admin:  DEBUG
    org.idea.shower:  DEBUG