file:
  path: https://www.yuan50697105.top:8002/img
#  path: http://123.56.78.153:8002/img
spring:
  profiles:
    include: wx,iot,mvc,dbconfig,storage
shower:
  storage:
    active: local
    local:
      address:
      storage-path:

