-- auto Generated on 2020-02-03
DROP TABLE IF EXISTS order_item;
CREATE TABLE order_item(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	create_time DATETIME COMMENT 'createTime',
	update_time TIMESTAMP COMMENT 'updateTime',
	create_user VARCHAR (50) COMMENT 'createUser',
	update_user VARCHAR (50) COMMENT 'updateUser',
	`type` INT (11) COMMENT '订单类型',
	order_id BIGINT (15) COMMENT '订单ID',
	order_no VARCHAR (50) COMMENT '订单编号',
	customer_id BIGINT (15) COMMENT '客户ID',
	customer_open_id VARCHAR (50) COMMENT '微信OPENID',
	customer_union_id VARCHAR (50) COMMENT '微型UNIONID',
	customer_nick_name VARCHAR (50) COMMENT '昵称',
	item_type INT (11) COMMENT '订单项目类型',
	item_order_no VARCHAR (50) COMMENT '子订单号',
	device_type INT (11) COMMENT '设备类型',
	device_id BIGINT (15) COMMENT '设备ID',
	device_code VARCHAR (50) COMMENT '设备编号',
	range_code VARCHAR (50) COMMENT '读取码',
	goods_info_id BIGINT (15) COMMENT '价目ID',
	goods_info_code VARCHAR (50) COMMENT '价目编号',
	time_price DECIMAL (13,4) COMMENT '时间定价',
	time_interval DECIMAL (13,4) COMMENT '时间计费间隔',
	time_total_price DECIMAL (13,4) COMMENT '时间用时总价',
	time_price_unit INT (11) COMMENT '时间定价单位',
	start_time DATETIME COMMENT 'startTime',
	end_time DATETIME COMMENT 'endTime',
	time_use_amount DECIMAL (13,4) COMMENT '时间使用量',
	water_price DECIMAL (13,4) COMMENT '水定价',
	water_space DECIMAL (13,4) COMMENT '水费计费间隔',
	water_unit INT (11) COMMENT '水费单位',
	water_total_price DECIMAL (13,4) COMMENT '总水费',
	total_price DECIMAL (13,4) COMMENT '总价',
	remain_price DECIMAL (13,4) COMMENT '充值剩余金额',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'order_item';
